### ISSUE TITLE
About the 'TF-IDF SA' in Ablation Study on SAG Modeling

### ISSUE THREAD

**Issue by seongeunryu** [Veason-silverbullet/DIGAT#2]
Dear sir,

I recently had the opportunity to read your article, and I must express my admiration for the insightful work you have presented.

While the provided code for the DIGAT model includes most of the ablation study code, it seems that the code for ablation TF-IDF SA regarding SAG Modeling is not included. 

If it's not too much trouble, could you also provide the code for this part? 
I am confident that this would be of great assistance to me.

Thank you very much for your attention to this matter. I look forward to your esteemed response.

Best regards,
Seongeun, Ryu

**Comment by Veason-silverbullet** [comment]
Dear Seongeun,

I am very very sorry that I cannot find this code as the project was done two years ago at the university (I first submitted the paper in Nov 2021, https://openreview.net/forum?id=t2vXlG7Oe5m). I can only try my best to help reproduce this ablation study on TF-IDF retrieval.

- Basically, TF-IDF calculates **sparse discrete** sentence embeddings, and SBERT calculates **dense continous** sentence embeddings. These two approaches function for the same goal. SAG construction with SBERT embedding is provided in construct_SAG.py.

- Based on the above preliminary, we can replace the SBERT embeddings computation on https://github.com/Veason-silverbullet/DIGAT/blob/0408369f20768b34c568f2db3937f276803a2868/construct_SAG.py#L97-L99 with TF-IDF embeddings. Specifically, I  used Sklearn TF-IDF feature extractor (https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html).

- Given the TF-IDF sentence features, you can choose dot-product or cosine function to calculate their similarity. Maybe you need to modify the code of https://github.com/Veason-silverbullet/DIGAT/blob/0408369f20768b34c568f2db3937f276803a2868/construct_SAG.py#L112

I think the code adaptation will be slight. If you have further questions, feel free to let me know in this issue or email me.

Cheers~

**Comment by seongeunryu** [comment]
Dear sir,

Thank you for providing a detailed explanation on how to reproduce SAG construction with TF-IDF embeddings. 
I was able to obtain meaningful results, and you may close the issue.

Thanks once again for your assistance :)

**Comment by Veason-silverbullet** [comment]
Dear Seongeun,

Glad to see this. Case closed. Thank you.
